version: "3"

services:
  db:
    image: "mongo:latest"
    volumes:
      - "mongo-vol:/data/db"
    networks:
      - project_name
  cms:
    image: agentejo/cockpit
    environment:
      COCKPIT_SESSION_NAME: cockpit
      COCKPIT_SALT: d5W8EmYfloKM
      COCKPIT_DATABASE_SERVER: "mongodb://db:27017"
      COCKPIT_DATABASE_NAME: cockpit_master
    depends_on:
      - db
    ports:
      - "8080:80"
    networks:
      - project_name

networks:
  project_name:
    driver: bridge

volumes:
  mongo-vol:
